server {
    listen 8080;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;

    client_max_body_size 4096m;

    location / {
        set                $frontend_backend http://react_app:8080;
        proxy_pass         $frontend_backend$request_uri;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location ~ ^/api/(.*)$ {
        set                $api_backend http://rust_admin:8000;
        proxy_pass         $api_backend/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    location /stream/ {
        set                $stream_backend http://rust_stream:8081;
        proxy_pass         $stream_backend$request_uri;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_buffering    off;
        proxy_read_timeout 120s;
    }
}
